config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get '/signup/user' => 'users#new'
  post '/signup/user' => 'users#create'

  get '/signup/landlord' => 'landlords#new'
  post '/signup/landlord' => 'landlords#create'

  get '/user_login' => 'sessions#new'
  post '/user_login' => 'sessions#create'

  get '/landlord_login' => 'sessions#new'
  post '/landlord_login' => 'sessions#create'

  delete '/user/logout' => 'sessions#destroy'
  delete '/landlord/logout' => 'sessions#destroy'

  resources :properties
  

  resources :landlords do
    resources :properties, only: [:index, :new, :show]
  end

  resources :users do 
    resources :properties, only: [:index, :show]
  end

  resources :users do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # validates :email, uniqueness: true
  # validates :username, uniqueness: true
  # validates :full_name, :username, :email, :email_address, :password, presence: true

  
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    belongs_to :property
end

app/models/landlord.rb
class Landlord < ApplicationRecord
    has_many :properties
    has_many :events, through: :properties
    has_secure_password
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :events
    has_many :users, through: :events
    belongs_to :landlord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events
    has_many :properties, through: :events
    has_secure_password

    def create 
        event = Event.create(event_params)
        redirect_to user_path(event.user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :verified_user
    before_action :verified_landlord
    helper_method :current_user
    helper_method :current_landlord

    def home

    end

    private

    def verified_user
        redirect_to '/' unless user_is_authenticated 
    end

    def verified_landlord
        redirect_to '/' unless landlord_is_authenticated
    end

    def user_is_authenticated
        !!current_user
    end

    def landlord_is_authenticated
        !!current_landlord
    end

    def current_user
        User.find_by(id: session[:user_id])
    end

    def current_landlord
        Landlord.find_by(id: session[:landlord_id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
    def new
        @landlord = Landlord.new
    end

    def create 
        if (@landlord = Landlord.create(landlord_params))
            session[:landlord_id] = @landlord.id 
            redirect_to landlord_path(@landlord)
        else
            render 'new'
        end
    end

    def show
        @landlord = Landlord.find_by(id: params[:id])
    end

    private
    
        def landlord_params
            params.require(:landlord).permit(
                :id, 
                :username, 
                :password, 
                :phone_number, 
                :email_address,
                :street_address_number,
                :street_address_name,
                :address_city,
                :address_state,
                :property_sales
                )
        end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

   def index 
      if params[:landlord_id]
         @properties = Landlord.find(params[:landlord_id]).properties
      else
         @properties = Property.all
      end
   end

   def new
      if params[:landlord_id] && !Landlord.exists?(params[:landlord_id])
         redirect_to landlords_path, alert: "Landlord not found"
      else
         @property = Property.new(landlord_id: params[:landlord_id])
      end
      # binding.pry
   end

   def create 
      @property = Property.new(property_params)
      @property.save
      redirect_to property_path(@property)
   end

   def show
      if params[:landlord_id]
         # @property = Property.find_by(landlord_id: params[:landlord_id])
         @property = Landlord.find(params[:landlord_id]).properties.find(params[:id])
      else
         @property = Property.find(params[:id])
      end
   end

   def property_params
      params.require(:property).permit(
         :landlord_id,
         :property_name,
         :manager_name,
         :phone_number,
         :street_address_name,
         :street_address_number,
         :address_city,
         :address_state,
         :event_type,
         :maximum_occupancy,
         :profit_expectation
      )
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verified, only: [:new, :create]

    def new
        @user = User.new
        @landlord = Landlord.new
    end

    def create 
        user = User.find_by(username: params[:user][:username])
        landlord = Landlord.find_by(username: params[:landlord][:username])

        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id 
            redirect_to user_path(user)
        else
            flash[:message] = "Invalid information provided for user, please try again. "
            redirect_to "/login"
        end

        if landlord && landlord.authenticate(params[:landlord][:password])
            session[:landlord_id] = landlord.id 
            redirect_to landlord_path(landlord)
        else
            flash[:message] = "Invalid information provide for landlord, please try again."
            redirect_to "/login"
        end
    end

    def destroy
        session.delete("user_id")
        session.delete("landlord_id")
        redirect_to root_path
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verified, only: [:new, :create]

    def index 

    end

    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def edit
        @user = User.find(params [:id])
    end



    private

    def user_params
        params.require(:user).permit(
            :id, 
            :full_name, 
            :username, 
            :password, 
            :phone_number, 
            :email, 
            :number_of_guests, 
            :budget, 
            :event_type, )
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/show.html.erb
<h1>this is the event show pate</h1>

app/views/landlords/_form.html.erb
<div class="container">
<p>Please provide your information below, and create your account: </p>
    <%= form_for @landlord do |f| %>
        <div class="form-group">
            <%= f.label :username %><br>
            <%= f.text_field :username, class:"form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :password , "Password:" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :phone_number %><br>
            <%= f.text_field :phone_number %>
        </div>

        <div class="form-group">
            <%= f.label :email_address %><br>
            <%= f.text_field :email_address %>
        </div>

        <strong>Address:</strong>
        <br>
        <br>
        <ul>
            <%= f.fields_for :address do |address_form| %>
                <li>
                    <%= address_form.label "Address number:"%>
                    <%= address_form.text_field :street_address_number %>

                    <%= address_form.label "Street name:" %>
                    <%= address_form.text_field :street_address_name %>

                    <%= address_form.label "City:" %>
                    <%= address_form.text_field :address_city %>

                    <%= address_form.label "State:" %>
                    <%= address_form.text_field :address_state %>
                </li>
            <% end %>
        </ul>

        <div class="action">
            <%= f.submit class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/landlords/show.html.erb
<div class="well profile">
    <div class="col-sm-12">
        <div class="col-xs-12 col-sm-8">
            <h2><%= @landlord.username %></h2>
            <p><strong>Phone Number: </strong><%= @landlord.phone_number %></p>
            <p><strong>Email: </strong><%= @landlord.email_address %></p>
            
    
        <div class="links">
            <p><%= link_to 'All properties', landlord_properties_path(@landlord) %></p>
            <p><%= link_to 'Create Property', new_landlord_property_path(@landlord) %></p>
        </div>
    
    </div>             
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!-- Compiled and minified CSS for Materialize-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <title>Event Finder!</title>
  </head>




  <body>
    <!-- <div class="container-fluid"> -->

<!-- navbar -->
<nav>

    <div class="nav-wrapper">
      <a class="brand-logo" href="<%= root_url %>/">EventFinder</a>
      <!-- conditions to see if user or landlord needs to register or login -->
      <% if (!current_user || !current_landlord) %>
        <a class="navbar-brand" href="<%= new_user_path %>">New User Signup</a>
        <a class="navbar-brand" href="<%= new_landlord_path %>">New Landlord Signup</a>
        <%= link_to "User Login!", user_login_path, class: "navbar-brand" %>
        <%= link_to "Landlord Login!", landlord_login_path, class: "navbar-brand" %>
      <% end %>
      <% if (current_user || current_landlord) %>
        <%= link_to "#{current_user.username}'s profile", user_path(current_user), class: "navbar-brand" %>
        <%= link_to "#{current_landlord.username}'s profile", landlord_path(current_user), class: "navbar-brand" %>
        <%= link_to "User Logout", user_logout_path, class: "navbar-brand", method: 'delete' %>
        <%= link_to "Landlord Logout", landlord_logout_path, class: "navbar-brand", method: 'delete' %>
      <% end %>
    </div>

  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>
          
    <div>  
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- Compiled and minified JavaScript for Materialize -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </body>
</html>

app/views/properties/_form.html.erb
<div class="container">
<p>Please submit the property you are interested to host: </p>
    <%= form_for @property do |f| %>
        <%= f.hidden_field :landlord_id %>
        <br>
        <%= f.label :property_name %>
        <%= f.text_field :property_name %>
        <br>
        <%= f.label :manager_name %>
        <%= f.text_field :manager_name %>
        <br>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
        <br>
        <strong>Address:</strong>
        <br>
        <br>
        <ul>
            <%= f.fields_for :address do |address_form| %>
                <li>
                    <%= address_form.label "Address number:"%>
                    <%= address_form.text_field :street_address_number %>

                    <%= address_form.label "Street name:" %>
                    <%= address_form.text_field :street_address_name %>

                    <%= address_form.label "City:" %>
                    <%= address_form.text_field :address_city %>

                    <%= address_form.label "State:" %>
                    <%= address_form.text_field :address_state %>
                </li>
            <% end %>
        </ul>
        <br>
        <%= f.label "Event type:" %>
        <%= f.text_field :event_type %>
        <br>
        <%= f.label "Maximum Occupancy:" %>
        <%= f.text_field :maximum_occupancy %>
        <br>
        <%= f.label "Profit expected: " %>
        <%= f.text_field :profit_expectation %>
        <br>
        <br>
        <div class="action">
            <%= f.submit class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/properties/index.html.erb
<h1>List of Properties to host an event</h1>

<br>
<p><%= link_to 'create property', new_landlord_property_path %></p>


<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td colspan="2">Larry the Bird</td>
                <td>@twitter</td>
            </tr>
        </tbody>
    </table>
</div>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<h3>Property Name: <%= @property.property_name %></h3>

app/views/users/_form.html.erb
<div class="container">

    <h1> Sign Up</h1>
    
    <%= form_for @user do |f| %>
        <p>Please provide your information below, and create your account:</p>
        <div class="form-group">
            <%= f.label :full_name %><br>
            <%= f.text_field :full_name, class:"form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :username %><br>
            <%= f.text_field :username, class:"form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :password , "Password:" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :phone_number %><br>
            <%= f.text_field :phone_number %>
        </div>

        <div class="form-group">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
        </div>

        <div class="form-group">
            <%= f.label :number_of_guests %>
            <%= f.text_field :number_of_guests %>
        </div>

        <div class="form-group">
            <%= f.label :budget %>
            <%= f.text_field :budget %>
        </div>

        <div class="form-group">
            <%= f.label :event_type %>
            <%= f.text_field :event_type %>
        </div>

        <div class="action">
            <%= f.submit class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="well profile">
    <div class="col-sm-12">
        <div class="col-xs-12 col-sm-8">
            <h2><%= @user.full_name %></h2>
            <p><strong>Phone Number: </strong><%= @user.phone_number %></p>
            <p><strong>Email: </strong><%= @user.email %></p>

        <div class="guest information">
            <h4><strong>guest information: </strong></h4>
                <div>
                    <p><span class="tags"><strong>Number of guests:</strong>  <%= @user.number_of_guests %></p>
                    <p><span class="tags"><strong>Event type:</strong>  <%= @user.event_type %></p>
                </div>
        </div>

        <div class="action">
            <p><%= link_to 'See all hosted properties', landlord_properties_path(@user) %></p>
        </div>
    </div>      
</div>